### ISSUE TITLE
Fluentd v0.12-debian installing v0.14.19

### ISSUE THREAD

**Issue by howardkr** [fluent/fluentd-docker-image#91]
I'm trying to build fluentd in my kubernetes cluster. I ran into many errors with v0.14 with buffering errors. I'm now trying to build using v0.12 - which is supposed to be clear of the errors, however, when using the fluent/fluentd:v0.12-debian image in my Dockerfile, i am still seeing an error. It looks like it's still installing v0.14 for some reason. 

Here is the error message: 

2017-07-28 19:23:39 +0000 [error]: #0 unexpected error while checking flushed chunks. ignored. error_class=NoMethodError error="undefined method `<' for nil:NilClass"
  2017-07-28 19:23:39 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.19/lib/fluent/plugin/output.rb:1231:in `block in enqueue_thread_run'
  2017-07-28 19:23:39 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.19/lib/fluent/plugin/buffer.rb:355:in `block (2 levels) in enqueue_all'
  2017-07-28 19:23:39 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.19/lib/fluent/plugin/buffer.rb:353:in `each'
  2017-07-28 19:23:39 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.19/lib/fluent/plugin/buffer.rb:353:in `block in enqueue_all'
  2017-07-28 19:23:39 +0000 [error]: #0 /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'

How should i proceed, so that i can eliminate the errors and successfully use v0.12?

**Comment by repeatedly** [comment]
Check https://docs.fluentd.org/v0.12/articles/plugin-management#plugin-version-management first.

**Comment by repeatedly** [comment]
> error="undefined method <' for nil:NilClass" 2017-07-28 19:23:39 +0000 [error]: #0 /var/lib/gems/2.3.0/gems/fluentd-0.14.19/lib/fluent/plugin/output.rb:1231:inblock in enqueue_thread_run'

BTW, is this error reproducible? I want to know your setting and traffic.

**Comment by howardkr** [comment]
Do you have any readily available info for which plugins are v12 compatible or what flags i can set to get them working? 

The plugins we are trying to utilize: 

fluent-plugin-s3 
fluent-plugin-systemd 
fluent-plugin-kubernetes_metadata_filter 
fluent-plugin-rewrite-tag-filter

Yes - I've been able to reproduce the error. Here's my docker file: 

`FROM fluent/fluentd:v0.12-debian

COPY /start.sh /home/fluent/start.sh

ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH

# !! root access required to read container logs !!
USER root

RUN buildDeps="sudo make gcc g++ libc-dev ruby-dev" \
&& apt-get update \
&& apt-get install -y --no-install-recommends $buildDeps \
&& gem install \
       fluent-plugin-s3 \
       fluent-plugin-systemd \
       fluent-plugin-kubernetes_metadata_filter \
       fluent-plugin-rewrite-tag-filter \
&& gem sources --clear-all \
&& SUDO_FORCE_REMOVE=yes \
   apt-get purge -y --auto-remove \
                 -o APT::AutoRemove::RecommendsImportant=false \
                 $buildDeps \
&& rm -rf /var/lib/apt/lists/* \
          /home/fluent/.gem/ruby/2.3.0/cache/*.gem

# Copy plugins
COPY plugins /fluentd/plugins/


ENTRYPOINT ["bin/sh", "/home/fluent/start.sh"]`

If you need any more info, please let me know.

**Comment by repeatedly** [comment]
> Do you have any readily available info for which plugins are v12 compatible

If the plugins don't depend on fluentd internal code, such plugin are v0.12 compatible.

**Comment by howardkr** [comment]
Thanks for the info. I have it successfully installing v12 with the plugins.
